CREATE DATABASE IF NOT EXISTS Accidentalidadbq;
USE Accidentalidadbq;
CREATE TABLE IF NOT EXISTS accidentebq (
	FECHA_ACCIDENTE VARCHAR (20),
    DIRECCION_ACCIDENTE VARCHAR(50),
	CONDICION_VICTIMA VARCHAR(20),
	GRAVEDAD_ACCIDENTE VARCHAR(50),
    CLASE_ACCIDENTE VARCHAR(20),
	SEXO_VICTIMA VARCHAR(5),
    EDAD_VICTIMA DECIMAL(10, 2),
    CANTIDAD_VICTIMAS DECIMAL(10, 2)
)